---
name: Make

on:
  schedule:
    - cron: '0 0 1 * *'
  pull_request:
    branches:
      - main

jobs:
  make:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x86_64
          # - aarch64

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build on Unix
        if: runner.os != 'Windows'
        shell: bash
        run: |
          source '.github/workflows/make.sh'
          instantfpc '.github/workflows/make.pas' build

      - name: Build on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          pwsh -File '.github/workflows/make.ps1'
